# Generated by Django 5.1.3 on 2024-11-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_inmueble"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="inmuebles/imagenes/")),
                (
                    "inmueble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="listings.inmueble",
                    ),
                ),
            ],
        ),
    ]
