# Generated by Django 5.1.3 on 2024-11-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_imageninmueble"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Listing",
        ),
    ]
