# Generated by Django 5.1.3 on 2024-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_delete_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inmueble",
            name="imagen",
        ),
        migrations.AddField(
            model_name="inmueble",
            name="calificacion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
