# Generated by Django 5.1.3 on 2024-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_alter_calificacion_estrellas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="estrellas",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
    ]
