# Generated by Django 5.1.3 on 2024-11-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_alter_calificacion_estrellas_delete_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="estrellas",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 estrellas"),
                    (2, "2 estrellas"),
                    (3, "3 estrellas"),
                    (4, "4 estrellas"),
                    (5, "5 estrellas"),
                ]
            ),
        ),
    ]
