# Generated by Django 5.1.3 on 2024-11-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0012_calificacion_fecha_creacion_calificacion_verificado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="estado",
            field=models.CharField(
                choices=[("disponible", "Disponible"), ("rentado", "Rentado")],
                default="disponible",
                max_length=20,
            ),
        ),
    ]
