# Generated by Django 5.1.3 on 2024-11-27 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_inmueble_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inmueble",
            name="estado",
        ),
    ]
