# Generated by Django 5.1.3 on 2024-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0014_remove_inmueble_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="estado",
            field=models.CharField(
                choices=[("disponible", "Disponible"), ("rentado", "Rentado")],
                default="disponible",
                max_length=20,
            ),
        ),
    ]
